spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/ceip_security?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    cache-names: usercache
  jackson:
    serialization:
      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: true
    mapper:
      AUTO_DETECT_FIELDS: false
      AUTO_DETECT_SETTERS: false
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://aip.baidubce.com/oauth/2.0/token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      authorized-grant-types: client_credentials
    resource:
      userInfoUri: https://graph.facebook.com/me
management:
  security:
    enabled: false
debug: true
logging:
  level:
    org.hibernate.SQL: debug





