spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.3.111:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://192.168.3.51:61616
  jms:
    template:
      delivery-mode: persistent
    pub-sub-domain: true

flyway:
  enabled: false
